# -*- coding: utf-8 -*-
"""Gas Prices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpZVxjITf0onkQJWnadOXM1g8ItatPYf
"""

import time
#@title Gas Prices
#1. Average Price per Year
#2. Average Price per Month
#3. Highest and Lowest Prices per Year
#4. List of Prices, Lowest to Highest
#5. List of Prices, Highest to Lowest
#6. Import gasprices.txt to make code work!

def read_gas_prices(file_name = 'gasprices.txt'):
  gas = open(file_name, 'rt')
  gastxt_lines = gas.readlines()
  gas_list = []
  for x in gastxt_lines:
    one_day = []
    one_day.append(int(x[0:2]))
    one_day.append(int(x[3:5]))
    one_day.append(int(x[6:10]))
    one_day.append(float(x[11:]))
    gas_list.append(one_day)
  return gas_list

def get_average_price_per_year():
  print()
  print('YYYY : Average')
  gas_list = read_gas_prices()
  year_list = set(x[2] for x in gas_list)
  avg_list = []
  for year in year_list:
    total = 0
    count = 0
    for x in gas_list:
      if x[2] == year:
        total += x[3]
        count += 1
    avg_list.append(float(total/count))
  for i, year in enumerate(sorted(year_list)):
    print(int(year), ':', float(avg_list[i]))

def get_average_price_per_month():
  print()
  print('MM YYYY : Average')
  gas_list = read_gas_prices()
  year_list = set(x[2] for x in gas_list)
  month_list = [4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3]
  avg_list = []
  for year in year_list:
    for month in month_list:
      total = 0
      count = 0
      for x in gas_list:
        if ((x[2] == year) and (x[0] == month)):
          total += x[3]
          count += 1
      if count != 0:
        avg = float(total/count)
        avg_list.append([month, year, avg])
  avg_list.sort(key = lambda x: (x[1], x[0]))
  for avg in avg_list:
    print(avg[0], avg[1], ':', avg[2])

def get_highest_and_lowest_prices_per_year():
  print()
  print('YYYY : Highest Price : Lowest Price')
  gas_list = read_gas_prices()
  year_list = set(x[2] for x in gas_list)
  for year in year_list:
    highest = 0
    lowest = 100
    for x in gas_list:
      if x[2] == year:
        if x[3] > highest:
          highest = x[3]
        elif x[3] < lowest:
          lowest = x[3]
    print(year, ':', highest, ':', lowest)

def generate_list_of_prices_lowest_to_highest():
  print()
  print('MM / DD / YYYY : Price')
  gas_list = read_gas_prices()
  for x in gas_list:
    x[0], x[1], x[2], x[3] = x[3], x[0], x[1], x[2]
  gas_list.sort()
  for x in gas_list:
    print(x[1],'/',x[2],'/',x[3],':',x[0])

def generate_list_of_prices_highest_to_lowest():
  print()
  print('MM / DD / YYYY : Price')
  gas_list = read_gas_prices()
  for x in gas_list:
    x[0], x[1], x[2], x[3] = x[3], x[0], x[1], x[2]
  gas_list.sort(reverse = True)
  for x in gas_list:
    print(x[1],'/',x[2],'/',x[3],':',x[0])

def print_runtime_summary():
  x = time.time()
  get_average_price_per_year()
  get_average_price_per_month()
  get_highest_and_lowest_prices_per_year()
  generate_list_of_prices_lowest_to_highest()
  generate_list_of_prices_highest_to_lowest()
  y = time.time()
  print(y - x)

def run_all_functions():
  print('Function 1: Average Price per Year')
  get_average_price_per_year()
  print()
  print('Function 2: Average Price per Month')
  get_average_price_per_month()
  print()
  print('Function 3: Highest and Lowest Prices per Year')
  get_highest_and_lowest_prices_per_year()
  print()
  print('Function 4: List of Prices from Lowest to Highest')
  generate_list_of_prices_lowest_to_highest()
  print()
  print('Function 5: List of Prices from Highest to Lowest')
  generate_list_of_prices_highest_to_lowest()
  print()
  print('Runtime Summary:', print_runtime_summary())

run_all_functions()