# -*- coding: utf-8 -*-
"""Phone Number from String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZR7Lvje2ZecLEgtJV85RD6MaM10Q7l8C
"""

#@title Assignment 12

def telephone(number):
  number = str(number)
  new_number = ''
  for i in number:
    if (i == 'A') or (i == 'a') or (i == 'B') or (i == 'b') or (i == 'C') or (i == 'c'):
      new_number = new_number + '2'
    elif (i == 'D') or (i == 'd') or (i == 'E') or (i == 'e') or (i == 'F') or (i == 'f'):
      new_number = new_number + '3'
    elif (i == 'G') or (i == 'g') or (i == 'H') or (i == 'h') or (i == 'I') or (i == 'i'):
      new_number = new_number + '4'
    elif (i == 'J') or (i == 'j') or (i == 'K') or (i == 'k') or (i == 'L') or (i == 'l'):
      new_number = new_number + '5'
    elif (i == 'M') or (i == 'm') or (i == 'N') or (i == 'n') or (i == 'O') or (i == 'o'):
      new_number = new_number + '6'
    elif (i == 'P') or (i == 'p') or (i == 'Q') or (i == 'q') or (i == 'R') or (i == 'r') or (i == 'S') or (i == 's'):
      new_number = new_number + '7'
    elif (i == 'T') or (i == 't') or (i == 'U') or (i == 'u') or (i == 'V') or (i == 'v'):
      new_number = new_number + '8'
    elif (i == 'W') or (i == 'w') or (i == 'X') or (i == 'x') or (i == 'Y') or (i == 'y') or (i == 'Z') or (i == 'z'):
      new_number = new_number + '9'
    else:
      new_number = new_number + i
  return new_number

telephone('456-456-HELP')