# -*- coding: utf-8 -*-
"""Population from File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTatxT230QnrHgHSWS_wecJRtt7pHuZ2
"""

population_file = open('USPopulation.txt', 'r')
lines = population_file.readlines()
lines = [int(y) for y in lines]
average_change = 0
x2 = 0
greatest = max(lines)
greatest2 = 0
least = min(lines)
lines.remove(least)
least2 = min(lines)
for x in lines:
  x = int(x)
  average_change += x - x2
  if ((greatest - x) > greatest2):
    greatest2 = greatest - x
  x2 = x
print('Average Change:', round(average_change/len(lines)))
print('Greatest Change:', greatest2)
print('Least Change:', least2 - least)