# -*- coding: utf-8 -*-
"""Zeller's Congruence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179t5_TTN1xDlJPJmwrH4pciYPH8KuOmg
"""

def find_day_of_week(day, month, year = 2022):
  q = day
  if ((month == 1) or (month == 2)):
    m = month + 12
  else:
    m = month
  K = year % 100
  J = year // 100
  h = ((q + ((13 * (m + 1)) // 5) + K + (K // 4) + (J // 4) + (5 * J)) % 7)
  if (h == 0):
    return "Saturday"
  elif (h == 1):
    return "Sunday"
  elif (h == 2):
    return "Monday"
  elif (h == 3):
    return "Tuesday"
  elif (h == 4):
    return "Wednesday"
  elif (h == 5):
    return "Thursday"
  elif (h == 6):
    return "Friday"

# DO NOT CHANGE any of the following test code
# TEST DRIVEN PROGRAMMING

# Calling the function
x = find_day_of_week(6, 11, 2022)
print("Test Case 1: 6-Nov-2022: ", x)

if (x == "Sunday"):
  print("Test Case 1 passed")
else:
  print("Test Case 1 failed")

# Test Case 2
x = find_day_of_week(14, 10, 2022)
print("Test Case 2: 14-Oct-2022: ", x)

if (x == "Friday"):
  print("Test Case 2 passed")
else:
  print("Test Case 2 failed")


# Test Case 3
x = find_day_of_week(12, 11)
print("Test Case 3: 12-Nov-2022: ", x)

if (x == "Saturday"):
  print("Test Case 3 passed")
else:
  print("Test Case3 failed")


# Test Case 4
x = find_day_of_week(10, 11, 2021)
print("Test Case 4: 10-Nov-2021: ", x)

if (x == "Wednesday"):
  print("Test Case 4 passed")
else:
  print("Test Case 4 failed")


# Test Case 5
x = find_day_of_week(4, 1, 2021)
print("Test Case 5: 4-Jan-2021: ", x)

if (x == "Monday"):
  print("Test Case 5 passed")
else:
  print("Test Case 5 failed")


# Test Case 6
x = find_day_of_week(29, 2, 2020)
print("Test Case 6: 29-Feb-2020: ", x)

if (x == "Saturday"):
  print("Test Case 6 passed")
else:
  print("Test Case 6 failed")


# Test Case 7
x = find_day_of_week(25, 12, 2019)
print("Test Case 7: 25-Dec-2019: ", x)

if (x == "Wednesday"):
  print("Test Case 7 passed")
else:
  print("Test Case 7 failed")


# Test Case 8
x = find_day_of_week(26, 4, 2008)
print("Test Case 8: April 26, 2008:", x)